[package]
name = "codevisual-web-launcher"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
prelude = { git = "https://github.com/kuviman/commons" }
codevisual-web = { path = "../codevisual-web" }
open = "1.2"
fs_extra = "1.0"
argparse = "0.2.1"
