install:
  - 'docker build --tag dock.rs https://github.com/kuviman/dock.rs.git'
  - 'docker run -dit -v $(pwd):/src --name dock.rs dock.rs bash'
script:
  - docker exec -it dock.rs cargo test --package codevisual
  - >-
    docker exec -it dock.rs cargo build --package codevisual --examples --target
    wasm32-unknown-emscripten
before_deploy:
  - docker exec -it dock.rs cargo doc --no-deps --package codevisual
  - >-
    docker exec -it dock.rs bash -c "echo '<meta http-equiv=refresh
    content=0;url=codevisual/index.html>' > target/doc/index.html"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
