language: rust
before_script:
  - cargo install cargo-web
script:
  - cargo test --package codevisual
  - (cd codevisual && cargo web test)
  - cargo test --package codevisual-demo
  - (cd codevisual-demo && cargo web test)
before_deploy:
  - cargo doc --package codevisual
  - echo '<meta http-equiv=refresh content=0;url=codevisual/index.html>' > target/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  fqdn: codevisual.kuviman.com
  on:
    branch: master
