language: rust
install:
  - sudo apt install libasound2-dev
before_script:
  - cargo install cargo-web
script:
  - cargo test --package codevisual
  - (cd codevisual && cargo web test)
  - cargo test --package codevisual-demo
  - (cd codevisual-demo && cargo web test)
before_deploy:
  - (cd codevisual-demo && cargo web deploy --release)
  - mv codevisual-demo/target/deploy target/deploy
  - cargo doc --package codevisual
  - mv target/doc target/deploy
  - echo '<meta http-equiv=refresh content=0;url=codevisual/index.html>' > target/deploy/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/deploy
  fqdn: codevisual.kuviman.com
  on:
    branch: master
