stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      language: rust
      cache:
        cargo: true
      install:
        - ./ci/install-native.sh
      script:
        - ./ci/test-native.sh
    - language: rust
      cache:
        cargo: true
      install:
        - ./ci/install-web.sh
      script:
        - ./ci/test-web.sh
    - stage: deploy
      language: rust
      cache:
        cargo: true
      install:
        - ./ci/install-web.sh
      script:
        - ./ci/deploy-web.sh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $TOKEN
        keep-history: true
        local-dir: target/deploy
        fqdn: codevisual.kuviman.com
