language: rust
before-install:
  - sudo apt update
install:
  - sudo apt install emscripten
  - sudo apt install libasound2-dev
  - rustup target add wasm32-unknown-emscripten
  - cargo install
script:
  - cargo test --verbose --package codevisual
  - >-
    cargo build --package codevisual --examples --target
    wasm32-unknown-emscripten
before_deploy:
  - cargo doc --no-deps --package codevisual
  - >-
    echo '<meta http-equiv=refresh content=0;url=codevisual/index.html>' >
    target/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
