[workspace]
members = [
    "codevisual",
    "codevisual-derive",
    "codevisual-web",
    "codevisual-web-launcher",
    "emscripten",
    "emscripten-sys",
    "prelude",
    "ugli",
    "web-build",
    "webby"]