[package]
name = "codevisual"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
gl = "*"

[target.'cfg(target_os="emscripten")'.dependencies]
emscripten-sys = "*"