[package]
name = "codevisual_commons"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[target.'cfg(target_os="emscripten")'.dependencies]
emscripten = { path = "../bindings/emscripten" }

[target.'cfg(not(target_os="emscripten"))'.dependencies]
rand = "*"