[package]
name = "ugli"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
gl = "*"
prelude = { path = "../prelude" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
image = "*"