[package]
name = "codewars2017_log"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
codevisual = { path = "../../.." }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[target.'cfg(target_os = "emscripten")'.dependencies]
codewars2017_web = { path = "../web" }